name: cv2talk
services:
  cache:
    container_name: cv2talk-cache-dev
    image: redis:8-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
  db:
    container_name: cv2talk-db-dev
    image: postgres:17-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  api:
    container_name: cv2talk-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    restart: unless-stopped

volumes:
  cache-data:
    driver: local
  db-data:
    driver: local
